name: hikka
services:
  worker:
    public: true
    build:
      context: .
      dockerfile: Okteto
    replicas: 1
    ports:
      - 8080
    resources:
      cpu: "1"
      memory: 3Gi
    volumes:
      - worker:/data
 
volumes:
  worker:
    size: 3Gi
